name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Enable Docker Buildx
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build image with cache
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        tags: ghactions-demo:latest
        load: true
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    # Scan built Docker image
    - name: Scan Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghactions-demo:latest'
        format: 'table'

    # Deploy locally using Docker
    - name: Run Docker container
      run: |
        docker stop ghactions-demo || true
        docker rm ghactions-demo || true
        docker run -d --name ghactions-demo -p 8000:8000 ghactions-demo:latest
