name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # روی VM اجرا میشه

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ghactions-demo:latest .

    - name: Run Docker container
      run: |
        docker stop ghactions-demo || true
        docker rm ghactions-demo || true
        docker run -d --name ghactions-demo -p 8000:8000 ghactions-demo:latest
